### ISSUE TITLE
Add title as a part of append_fs, append_encodings and append_src

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal.reporter#120]
### Feature description

In every module, we have to add `card$append_text("Filter State", "header3")` before the `append_fs` call.
Please make the title call as a part of the `appenf_fs` call and take into account when there is no filter state to display.

EDIT: apply this to `append_fs`, `append_encodings` and `append_src` also.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Polkas** [comment]
please do it parallel with https://github.com/insightsengineering/teal.reporter/issues/88#issuecomment-1191392779
