### ISSUE TITLE
[Feature Request]: Allow htmlwidgets Plots in Report

### ISSUE THREAD

**Issue by armcn** [insightsengineering/teal.reporter#129]
### Feature description

The `append_plot` method doesn't support htmlwidgets like plotly. This would be very useful because plotly is heavily utilized in pharma shiny apps. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Polkas** [comment]
@armcn there is already a way to support plotly in many scenarios (I know it is NOT cover all). Very often the plotly plot is build over the regular ggplot with the `ggplotly` function. Then to the app output you still pass what is returned by `ggplotly` but to the teal.reporter you pass the base ggplot object.

```
library(plotly)
library(ggplot2)

set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]

p <- ggplot(data = d, aes(x = carat, y = price)) +
  geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
  geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)

ggplotly(p)
```
