### ISSUE TITLE
Adding table of content to report

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/teal.reporter#130]
![image](https://user-images.githubusercontent.com/3692541/185015696-ca941953-add0-42b1-9576-493a91bb73d8.png)

Dear core dev fam

I was wondering if it is possible to add a navigation bar to the report?

**Comment by Polkas** [comment]
I will propose a more comprehensive solution for toc where it could be TRUE or FALSE. The additional arguments like `toc_float` are document type specific so they could not be easy shared and require another layer of complexity. From the beginning we want to have a simple interface and code base so I will recommend such solution. We want to show all inputs so the toc_float input will have to be dynamic and visible only for html document type. On the other hand setting it in behind will be not transparent.
