### ISSUE TITLE
Not display SRC in the final report by default

### ISSUE THREAD

**Issue by kumamiao** [insightsengineering/teal.reporter#131]
Is it possible to not display the R code in the generated final report by default (in the pdf, html, word and pptx files)? The reason is the reports will be delivered to stakeholders, who are not programmers and would only need the analysis results instead of the source code. The app developer will still be able to retrieve the code from the Rmd to trace back or turn on the SRC in the Rmd if needed, maybe something like

```
```{r, results='hide'}
print("<R code here>")
```

**Comment by Polkas** [comment]
have to be applied here https://github.com/insightsengineering/teal.reporter/blob/785e7d19287bf8bc27bc2b9ee2d37ab710402bb1/R/TealReportCard.R#L25

we might need additional append_text option

**Comment by mhallal1** [comment]
@kumamiao Given this issue and this one https://github.com/insightsengineering/teal.reporter/issues/95, I wonder which solution you have in mind:
1) Never show the R code in the report. If the user wants to see the code, they can look at `.Rmd` file.
2) Include a global button in the download module to show/hide the code in the report but always keep it in the `.Rmd` file.

**Comment by kumamiao** [comment]
From clinical report perspective, 1 would be sufficient; but I would vote for 2 to be more flexible for general usage, and set the default to hide. @donyunardi thoughts?

**Comment by donyunardi** [comment]
I vote for 2. 
It will provide more flexibility to the feature.
