### ISSUE TITLE
Freeze Add Card button when adding card is in progress

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.reporter#137]
I assume for backlog? 

When adding a card takes a long time you get the following screen:

![image](https://user-images.githubusercontent.com/15201933/193833062-5a306a23-b5af-44b3-a538-03dd4f68f794.png)

But you can still click on the "Add Card button" which leads to multiple cards being added:

![image](https://user-images.githubusercontent.com/15201933/193833260-9a2a7fae-9abc-4b95-9ded-5af942fda76c.png)

**Comment by donyunardi** [comment]
> I assume for backlog?
Yes, moving to backlog.

**Comment by donyunardi** [comment]
As @nikolas-burkoff pointed out, this is taken care with #151.
Closing.
