### ISSUE TITLE
Inconsistent confirmation dialogs

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.reporter#138]
I assume for backlog?

When deleting the whole report you get one type of dialog:

![image](https://user-images.githubusercontent.com/15201933/193833858-f8737744-b7bf-4611-b2e7-e9905e95f2bb.png)

When deleting a single card you get a different alert:

![image](https://user-images.githubusercontent.com/15201933/193834049-c29ce979-7059-4e04-93a3-006437c3ac6a.png)

Can these be the same style?

**Comment by lcd2yyz** [comment]
Great suggestion! Let's go with the first style (the one used for whole report).

**Comment by Polkas** [comment]
The source for the two messages is different. The first is generated by shiny on the server side, and the latter by the web browser on the front side.
[The web browser confirm box can not be styled with css.](https://stackoverflow.com/a/6185246). So we need other mechanics like jquery and custom HTML in the DOM.

We must be cautious that the css styling for different bootstrap versions will look consistent.

**Comment by asbates** [comment]
So instead of generating the confirm dialog via JS, can't we send a message to the shiny server, then render from Shiny? That way both dialogs are rendered via the same method. And bootstrap versions won't be an issue because both dialogs will have the same styling.

**Comment by Polkas** [comment]
@asbates thanks for contribution. Yes, it is a nice option and we already send the message to the shiny server via`Shiny.setInputValue`.
Then we will transfer the functionality to remove the card to the server side, partly.
We will not only remove the card on the server side but print the modal from which we will take the answer and lastly remove it or not. It looks like It will require two different observers the new one to print the modal and the current one which will be triggered by the first one.
It works, the only cost is to have an additional observer in the nested structure.
