### ISSUE TITLE
Stargazers and Forkers plot

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal.reporter#144]
In the `pkgdown` url of `teal.reporter`: https://insightsengineering.github.io/teal.reporter/
The Stargazers and Forkers plot in the main page has a non-consistant y-axis count:
![Screenshot from 2022-10-06 14-52-44](https://user-images.githubusercontent.com/86970066/194318605-ebd6589b-ee3b-4fbb-a107-1856bdf997a7.png)

**Comment by donyunardi** [comment]
I think the issue is with startchart.cc.
Not sure if we can do something about this.
