### ISSUE TITLE
Inconsistent Card Titles

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.reporter#150]
From https://github.com/insightsengineering/coredev-tasks/issues/387 by @BLAZEWIM 

Steps to reproduce:
1. Launch "patient-profile" from teal.gallery
1. Click the "Lab values" module
1. Add Reporter Card by clicking the plus sign and clicked "Add Card" when the modal appears
1. Click the "Prior medication" module
1. Add Reporter Card by clicking the plus sign and clicked "Add Card" when the modal appears
1. Click the "Reporter previewer" module

![image](https://user-images.githubusercontent.com/8597300/194972083-3139b5e7-4a16-4c46-98c6-70668905d1c4.png)

Should the card title format be more consistent, i.e. `<appname> <module name> Table` ?

**Comment by donyunardi** [comment]
Linking with this comment:
https://github.com/insightsengineering/teal.reporter/issues/94#issuecomment-1324700151

The solution is to pass `label` from `tm_g_XXX` to `srv_g_xxx` of all modules using reporter to accomplish this task.

`label` is already part of srv argument:
https://github.com/insightsengineering/teal.modules.clinical/blob/main/R/tm_t_pp_laboratory.R#L288-L301

**Comment by kartikeyakirar** [comment]
> Should the card title format be more consistent, i.e. <appname> <module name> Table ?

Maintaining tittle <appname><module name>  Table/Plot can result in repetitive terms, such as "plot plot," as illustrated in the case of the "Bivariate Plots" module 'tm_g_bivariate', leading to redundant titles.

e.g
**Exploratory Bivariate Plots Plot**

option1 : Consistently retain only the <appname> <module name> while eliminating the trailing plot/table terms.
option2: Develop logic to detect whether the module yields a plot or table and then verify if the same term is already present in the title as a trailing term.

@donyunardi Let me know your thoughts on this?

<img width="942" alt="image" src="https://github.com/insightsengineering/teal.reporter/assets/6700955/965d1783-9d22-4cc1-8a54-27a129857d6b">

<img width="940" alt="image" src="https://github.com/insightsengineering/teal.reporter/assets/6700955/9d2d7c53-3fc1-47b2-a0ec-f9738352a645">

<img width="945" alt="image" src="https://github.com/insightsengineering/teal.reporter/assets/6700955/e2c22c0a-1c45-4f9e-93de-24902ec3c141">

**Comment by kartikeyakirar** [comment]
Also I don't think we need to include <appname>.

**Comment by donyunardi** [comment]
Now that we've completed https://github.com/insightsengineering/teal.modules.clinical/pull/835, I feel that we don't need this anymore.

Users now have the freedom to either consistently name the card or utilize the default title/label provided by the module. Any updates to the default values should be discussed at the module level.

I believe we can consider this matter closed.
Thoughts?

**Comment by kartikeyakirar** [comment]
Agreed. closing this.
