### ISSUE TITLE
Automatically wrap up the long code in the Report

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.reporter#169]
@nikolas-burkoff I think I found the solution to automatically wrap up the R code in the Report.
We need the formatR package and additional knitr global option. We could easily add this option as now we support global knitr ones.

`knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)`

or tidy = "styler"

Source: https://stackoverflow.com/a/74502546/5442527

**Comment by averissimo** [comment]
Optimal line length: https://baymard.com/blog/line-length-readability

**Comment by chlebowa** [comment]
Acceptance criteria:

Figure out how to neatly wrap code in all report formats available.

**Comment by m7pr** [comment]
Should we change global knitr options in here?
https://github.com/insightsengineering/teal.reporter/blob/main/R/Renderer.R#L38

**Comment by kartikeyakirar** [comment]
> knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)

This has dependencies for formatR, but the formatting looks good for other formats. Should we add it for all formats or just for PDF?

**Comment by m7pr** [comment]
nah, just put it in the default global_knitr options and this will be applied to every format
