### ISSUE TITLE
cancel button color in a modal

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.reporter#179]
linked to https://github.com/insightsengineering/teal.reporter/pull/178

Proposed by @chlebowa.
The red color for cancel buttons seems not not be suited. Why stopping the action is dangerous, I think grey will be more suited. On the other hand a removal button should be red.

![image](https://user-images.githubusercontent.com/10676545/208886498-c8628329-d694-42f0-9343-4cdd54547e3a.png)

**Comment by chlebowa** [comment]
I agree: grey for "abort" and red for "take irreversible action" 👍
