### ISSUE TITLE
[Bug]: "Download" small typo

### ISSUE THREAD

**Issue by PashaMS** [insightsengineering/teal.reporter#180]
### What happened?

Small misspelling of "Download" :)
![image](https://user-images.githubusercontent.com/53493382/217611794-70e0d7ff-af88-4bd1-b926-876b8af41998.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Thanks for catching this! 
The good news is that we fixed this already in our edge version: https://github.com/insightsengineering/teal.reporter/pull/174

Please continue to let us know if you see something like this again =)
