### ISSUE TITLE
[Feature Request]: Nicer table formatting in PPT outputs 

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal.reporter#185]
Users report that slides generated from Teal apps at the moment are not really ready-to-use. 
Examples attached [input_20230317191236450.pptx](https://github.com/insightsengineering/teal.reporter/files/11300060/input_20230317191236450.pptx)

Table from ppt generated by teal app at default
![image](https://user-images.githubusercontent.com/78242757/233757076-19bbc8c7-c403-4a73-a20c-5fe8f0698c1a.png)

Table from ppt generated by teal app after dramatically reducing for font size
![image](https://user-images.githubusercontent.com/78242757/233757142-d8ac94a9-6b3e-4ea4-b5e9-af109aa5ac77.png)

Notable issues include
- Weird default fontsize
- Table formatting is not as nice as shown in teal app 
- Table is in the printed text format, difficult to make any additional manipulation or formatting

User wants to see
- Expecting to see table in slides formatted similarly to how it's displayed in teal app
- Table contents in slides should be easily editable (eg. adjust column width, change styling of content, removing selective contents)
- Ideally enable reasonable pagination

Suggestion - should look towards Roche internal package called `autoslideR` for inspiration and potential solutions

**Comment by chlebowa** [comment]
Acceptance criteria:

Research the `autoslideR` package (Roche internal),m it can probably solve the complicated requirements like exporting a table (not text) etc..

Ensure font sizes in reports are more suitable.

**Comment by chlebowa** [comment]
NOTE: Feel free to separate into 2 issues if research and implementation are too much.

**Comment by puzeng** [comment]
Is there a consideration about converting into flextable object and work from there for nicer formats?

**Comment by kartikeyakirar** [comment]
I'm having difficulty finding the `autoslideR` package. Could someone please provide assistance in locating this package?

**Comment by lcd2yyz** [comment]
> I'm having difficulty finding the `autoslideR` package. Could someone please provide assistance in locating this package?

@kartikeyakirar Package is located in internal repos and not yet published externally. I will share link privately.

**Comment by kartikeyakirar** [comment]
Hey @donyunardi and @lcd2yyz 

In autoslideR there custom color-based theme for flextable, which isn't exactly the same as what's displayed on the dashboard but does enhance the overall look for reporting purposes. We'd like your input on whether we should include this theme or stick with the simpler format shown on the dashboard.

Dashboard
<img width="1070" alt="Screenshot 2023-09-07 at 7 22 17 PM" src="https://github.com/insightsengineering/teal.reporter/assets/6700955/48bb65c9-e7c9-4b1a-b0bf-692faec1ccd8">

Report after flextable addition
<img width="1342" alt="Screenshot 2023-09-07 at 7 23 27 PM" src="https://github.com/insightsengineering/teal.reporter/assets/6700955/c66c47fd-2ca2-4478-b800-041d57990d40">

Blue Theme from autoslideR:
<img width="706" alt="Screenshot 2023-09-07 at 7 24 26 PM" src="https://github.com/insightsengineering/teal.reporter/assets/6700955/69db5e9e-5d2a-4dd9-a2b5-54c1261baaa7">

OrangeTheme from autoslideR:
<img width="706" alt="Screenshot 2023-09-07 at 7 25 07 PM" src="https://github.com/insightsengineering/teal.reporter/assets/6700955/28dc9926-c8a0-4725-8616-d2ffa7d56272">

**Comment by donyunardi** [comment]
Personally, I would like to keep the format as simple as possible. I believe that coloring is a matter of personal preference, and users can change it themselves later if they wish.

On the simple format shown in the dashboard, can we add an outer border and a horizontal line in the inner output? I was reading about flextable, and it looks like we can do something like this:
https://ardata-fr.github.io/flextable-book/define-visual-properties.html#add-lines

If we can, then I think it will further improve the looks when we keep it simple.

**Comment by lcd2yyz** [comment]
Agree with @donyunardi to keep it simple. 
And from above website, my preference is to use the [`theme_booktabs()`](https://davidgohel.github.io/flextable/reference/theme_booktabs.html) as default. This has the closest resemblance to the formal reporting we deliver from clinical data analysis.

**Comment by kartikeyakirar** [comment]
@lcd2yyz and @donyunardi, I appreciate your valuable feedback. I have implemented some changes using [theme_booktabs()](https://davidgohel.github.io/flextable/reference/theme_booktabs.html), including the addition of borders and horizontal lines. You can see the updated format in this image:
<img width="469" alt="image" src="https://github.com/insightsengineering/teal.reporter/assets/6700955/477ceaa3-69ee-41d2-b950-74677c6febbf">

Furthermore, I've introduced an additional issue/feature as an extension to the one we discussed earlier. You can find more details here: https://github.com/insightsengineering/teal.reporter/issues/212

**Comment by lcd2yyz** [comment]
Looking very nice! 
Are you able to test if outputted in .ppt or .docx, is the table fully editable? eg. able to adjust columns, add/delete rows/columns easily, etc.

**Comment by kartikeyakirar** [comment]
> Are you able to test if outputted in .ppt or .docx, is the table fully editable?

Flextables can be fully edited in both PowerPoint and document formats.

https://github.com/insightsengineering/teal.reporter/assets/6700955/1c01b9e6-381c-4418-a261-af4d0a1d2dc4

**Comment by puzeng** [comment]
> > Are you able to test if outputted in .ppt or .docx, is the table fully editable?
> 
> Flextables can be fully edited in both PowerPoint and document formats.
> 
>  Screen.Recording.2023-09-09.at.12.15.23.AM.mov

It's wonderful to see this change as user from study team who wants to use this feature for future slides preparation! I did a similar way to allow the tables as shown as flextable by only altering in Renderer.R:
`tableBlock2md = function(block) {
      basename_table <- basename(block$get_content())
      file.copy(block$get_content(), file.path(private$output_dir, basename_table))
      sprintf("```{r echo = FALSE, message = FALSE, ft.left = 0.3, ft.top = 1}
              \n
              flextable::autofit(flextable::fontsize(flextable::fontsize(rtables::tt_to_flextable(readRDS('%s')), size = 6, part = 'body'), size = 8, part = 'header'))
              \n```", basename_table)
    }`
@kartikeyakirar Your codes seemed to provide more flexibility in terms of fitting. Just a tiny curiosity here, did you also test in table with long length? Typically, table of adverse events by preferred terms could be very long. Primarily here, I'm trying to image how zooming-out works on the long tables. I guess pagination could be the next feature to consider.

**Comment by kartikeyakirar** [comment]
> did you also test in table with long length? Typically, table of adverse events by preferred terms could be very long.

Accommodating a very lengthy table within a single slide is an extremely challenging task, and it's nearly impossible to adjust such a substantial amount of content in a single slide. Manual editing may be helpful in certain scenarios, but finding an optimal solution for handling very long tables remains elusive.


Here is the table: [table_20230911_114923.pdf](https://github.com/insightsengineering/teal.reporter/files/12572848/table_20230911_114923.pdf). This is a demonstration of how this content is displayed in a slide, which you can access here: 

https://github.com/insightsengineering/teal.reporter/assets/6700955/a4591aff-4aa8-4d42-a98d-f82fdcbcd3fd

**Comment by lcd2yyz** [comment]
Hi @puzeng, I agree with @kartikeyakirar that enabling pagination will be quite challenging at this point, given that `teal.reporter` needs to accommodate more than just .ppt, but also various other output format including html (which should not need pagination), word/pdf (which probably will need different rules for pagination) compared to ppt. 
Also I imagine how user want to split the pages may be quite different. For example, maybe for some sections, only want to display 10 rows per this page, and use the rest of the space to add annotation/explanation text, but for other sections, want to display as many rows as possible, to simply display the statistics. In such scenario it might be easier to split the tables rather than merge/combine two already split tables, if it will involve manual work anyways.

If you still feel strongly about this feature, please open an new issue, with your suggested approach and/or example code, if you already have it. Then we'll consider for future development.
