### ISSUE TITLE
Color scheme for disabled button

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.reporter#187]
> Felt like we can do better when the button is disabled (blue and grey just not pleasing to the eye).
> 
> ![image](https://github.com/insightsengineering/teal.reporter/assets/8597300/0514b3f0-4dee-4d03-ab38-070defd72242)
> 
> ![image](https://github.com/insightsengineering/teal.reporter/assets/8597300/5e543e1f-44fa-4e7c-a853-ce53a08f1f41)
> 

_Originally posted by @donyunardi in https://github.com/insightsengineering/teal.reporter/issues/186#issuecomment-1550676354_

**Comment by chlebowa** [comment]
Acceptance criteria:

Modify CSS of the buttons in the dialogs to ensure good contrast/readability.
