### ISSUE TITLE
[Bug]: Long Code Lines Partially Hidden in PDF Report

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.reporter#199]
### What happened?

A bug happened!
In the exploratory app, when generating a PDF report for the **Missing data** tab, the code lines within the plot section are lengthy and partially hidden. Although the code is accessible in other formats, in the PDF report, it does not display entirely. As a solution, we need to find a way to adjust the code layout within the given section to ensure it is fully visible in the generated PDF report.

Sample report
[input_20230803054235201.pdf](https://github.com/insightsengineering/teal.reporter/files/12247277/input_20230803054235201.pdf)

Screenshot
![image](https://github.com/insightsengineering/teal.reporter/assets/6700955/abfac21b-fb4e-483b-a61c-39c55b7de68f)

**Comment by lcd2yyz** [comment]
Related to https://github.com/insightsengineering/teal.reporter/issues/169

**Comment by gogonzo** [comment]
closed in favour of #169
