### ISSUE TITLE
Release `teal.reporter` to CRAN

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.reporter#201]
### Summary
The objective is to make `teal.reporter` available on CRAN. 
I ran R CMD check locally and everything looks good so we probably don't need to do a preliminary release before pushing to CRAN.

### Acceptance Criteria
* Add/Confirm the `--as-cran` option in CICD pipeline
* R CMD Check passed or create new issue to fix
  * If there is an issue, then we'll need a preliminary release
  * Might as well perform the README task and the vignettes grouping
  * Perform release activities (full version bump and git tag)
* Push to CRAN

**Comment by donyunardi** [comment]
> Add/Confirm the --as-cran option in CICD pipeline

Confirmed ✅ 
https://github.com/insightsengineering/teal.reporter/blob/main/.github/workflows/check.yaml#L30

**Comment by m7pr** [comment]
![image](https://github.com/insightsengineering/teal.reporter/assets/133694481/9ab6327c-e8c0-49c1-a1bb-6db142781ecd)

The last step is accepting the e-mail from CRAN by package maintainer @gogonzo

**Comment by gogonzo** [comment]
Confirmed. Let's wait for the response from the CRAN team now

**Comment by donyunardi** [comment]
Package now in CRAN:
https://cran.r-project.org/web/packages/teal.reporter/index.html
