### ISSUE TITLE
Fix CRAN issues

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.reporter#208]
Please do not start the description with "This package", package name,
title or similar.

The Description field is intended to be a (one paragraph) description of
what the package does and why it may be useful. Please add more details
about the package functionality and implemented methods in your
Description text.

Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: --> 'shiny'
Please note that package names are case sensitive.

The LICENSE file is only needed if you have additional restrictions to
the license which you have not? In that case omit the file and its
reference in the DESCRIPTION file.

"Using foo:::f instead of foo::f allows access to unexported objects.
This is generally not recommended, as the semantics of unexported
objects may be changed by the package author in routine maintenance."
Used ::: in documentation:
      man/Archiver.Rd:
         archiver <- teal.reporter:::Archiver$new()
      man/ContentBlock.Rd:
         block <- teal.reporter:::ContentBlock$new()
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("TRUE")
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("True")
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("off")
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("n")
      man/conv_str_logi.Rd:
         teal.reporter:::conv_str_logi("sth")
      man/FileArchiver.Rd:
         archiver <- teal.reporter:::FileArchiver$new()
      man/FileBlock.Rd:
         block <- teal.reporter:::FileBlock$new()
      man/JSONArchiver.Rd:
         card1 <- teal.reporter:::ReportCard$new()
      man/JSONArchiver.Rd:
         reporter <- teal.reporter:::Reporter$new()
      man/JSONArchiver.Rd:
         archiver <- teal.reporter:::JSONArchiver$new()
      man/JSONArchiver.Rd:
         blocks <- teal.reporter:::Reporter$new()$
[... truncated]
Please omit one colon.

Please fix and resubmit.

**Comment by m7pr** [comment]
That's a quick reply, and luckily not much of a hassle !

**Comment by chlebowa** [comment]
`:::` in documentation will be a HUGE hassle, at least in `teal.slice`.

**Comment by gogonzo** [comment]
New comment (new reviewer)

> Please always write package names in the title in single quotes. e.g:
--> 'shiny'
Please note that package names are case sensitive.

**Comment by m7pr** [comment]
ah, that is so stupid :) will update and resubmit
