### ISSUE TITLE
[Question]: Placement of `card_template()` function.

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.reporter#226]
### What is your question?

To include card labels, the `add_card_button_srv` function allows you to specify the `card_fun` along with a label parameter for customizing the card's title and content. This feature enables you to utilize the label shiny input and incorporate it into your `card_fun` to set the title.

When it comes to teal modules, each module has its own  structure for the `card_fun`, but there are common elements shared across all card_function that can be standardized within a `card_template `function. You can find an example of this in the following code:

[Teal Reporter - card_template function](https://github.com/insightsengineering/teal.reporter/blob/198_card_labels%40main/R/utils.R#L299-L332)

This card_template function can be further encapsulated to suit specific requirements, as demonstrated here:

[Teal Goshawk - customized card_template](https://github.com/insightsengineering/teal.goshawk/blob/198_card_labels%40main/R/utils.R#L35-L79)

The challenge lies in deciding where to place the card_template function, as keeping it within teal.reporter adds teal as a dependent package. Here are a few suggestions:

**Option 1:**
Move the `card_template() `function to teal as an exported function. Instead of teal.reporter.

**Option 2:**
Create a separate `card_template` for each module (e.g., tmc, tmg, tmh) to ensure module-specific customization. 

**Option 3:**
Consider adding teal as a dependency to teal.reporter to retain the card_template function.

**Comment by kartikeyakirar** [comment]
@insightsengineering/nest-core-dev Please share your thoughts or questions regarding

**Comment by m7pr** [comment]
Why do we need teal package for that?

**Comment by kartikeyakirar** [comment]
Because the `card_template` function relies on the `teal package`, it utilizes the `TealReportCard `R6 class, which has been relocated to the `teal `package.

**Comment by m7pr** [comment]
Alrighty, so it's rather clear that you need to include it (card_template)
in teal and we don't need a separate discussion about it. No need for extra
dependencies in teal.reporter then

**Comment by kartikeyakirar** [comment]
I've moved the template function to the `teal` repository. You can find the corresponding pull request at this link: https://github.com/insightsengineering/teal/pull/933.
