### ISSUE TITLE
Pre-release activities

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.reporter#237]
### Summary

Please carry out these tasks in preparation for CRAN release:

* Review and update:
    * README.md (check example code)
    * NEWS.md
* Run urlchecker::url_check() to identify broken links and fix
* Review functions:
    * @example tag, make sure it runs, fix if otherwise
    * Make sure functions has @return tag to document the return value
    * no \dontrun tag, replace with if(interactive()) if needed
* Sanity check of all vignettes, make sure there is no typo, no wrong format, etc.
* Run R CMD check --as-cran make sure everything pass
* Package `Title` is not duplicated in Package `Description` in DESCRIPTION file (e.g. this happens in teal.slice currently)
* All package names in `Title` and `Description` fields of DESCRIPTION file are quoted with `'`
* You have checked the Package Release Template https://github.com/insightsengineering/teal.reporter/pull/205/files
* Make sure there are no `:::` in examples
    * if you need to retain the example that uses `:::`, use `getFromNamespace()` function.
* Make sure all `teal.*` mentions are lower-cased and quoted
* Make Sure inst/WORDLIST is minimalized
* Make sure non-exported functions do not have examples
* Make sure each link to our documentation hosted with pkgdown on github pages do not have `/main/` in the address but it has `/latest/` instead, so we always expose the documentation of the latest release and not what's currently on main branch but not yet released

**Comment by averissimo** [comment]
Also needs:

- Correct author list
- Change `teal.R` to remove `@docType` in favor of `"_PACKAGE"`
- Spellcheck `NEWS.md` `catched` -> `caught`
  - Update `WORDLIST``
    - (should remove `roche`, `hallal`, `catched`)
