### ISSUE TITLE
R CMD CHECK note

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.reporter#288]
```
* checking files in ‘vignettes’ ... NOTE
Files named as vignettes but with no recognized vignette engine:
   ‘vignettes/_setup.Rmd’
(Is a VignetteBuilder field missing?)
```

- [ ] fix it
- [ ] if fixable - add appropriate regexp to the [r-cmd-check-note blocklist](https://github.com/insightsengineering/teal.reporter/blob/4fefa7ebac08caac2ca7b6588e497613ac4676fc/.github/workflows/check.yaml#L33-L41) in all our repos

**Comment by pawelru** [comment]
Hey @llrs-roche, I have linked your PR as this essentially solves the issue but can you also have a look at the CI part so that it would be automatically captured by CI on commit (instead of external testing service)

**Comment by llrs-roche** [comment]
Oh, I didn't realize there was already an issue for this.
The list on the blocklist seems to only use the official R message, not the specific note/warning/error (if any(. I'll try to see if it is possible to capture that.

**Comment by pawelru** [comment]
That list is collapsed into one string with `|` and then there is a simple regular expression on the R CMD CHECK output. It means that we just need to extend it with yet another element against that use case.
The good/bad thing about this is that that list is defined for each repo. It's good because it allows for exceptions. It's bad because if we want to extend the list for all pkgs then it means a lot of PRs. I know IDR team has some magic tool that does such propagation - in such case let's create a task and explain in detail what and where. They are doing this periodically when number of requests reach some threshold (whatever it is). But it's important to note it.
