### ISSUE TITLE
Report previewer notifications

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.reporter#53]
When cards are added to a report it would be neat if you could get a notification on the Previewer tab (or elsewhere) with the number of new cards added to the report since you last clicked on the previewer being shown

![image](https://user-images.githubusercontent.com/15201933/169849014-68ce8218-200e-4b6c-b333-8fb687e7e57e.png)

like with notifications on your phone

**Comment by nikolas-burkoff** [comment]
So this may be quite hard to do as at the moment the add card button is inside the modules (rather than directly in teal) but teal is where the "previewer" tab lives - so we need to pass the information that a card was added to teal. When the previewer tab is pressed that also needs to be communicated to teal so the notification can disappear.

It might be possible to do this using `length(reporter$get_cards())` which states how many cards there are now and you could imagine a reactive in teal which uses this information to know whether to display the notification and to "reset" once the previewer is clicked on. It will also add complexity as it will make the previewer teal module have to behave differently to other modules which isn't the case now and may add a lot of complexity for not much functionality.

**Comment by donyunardi** [comment]
Thanks for the investigating this @nikolas-burkoff.
It just doesn't seem that it would worth the effort to go through all of this.
As of now, I'm leaning toward closing this issue.

Let me confirm with  @lcd2yyz before closing this.

**Comment by Polkas** [comment]
I think we could redefined it and show in the same way how many cards was already added. WHat you think:)?

**Comment by donyunardi** [comment]
Yeah, let's do that instead!

**Comment by donyunardi** [comment]
Sure, let's redefine this.

>  show in the same way how many cards was already added

Are we thinking about enhancing the notification that shows on the bottom right hand corner when a new card is added?

**Comment by Polkas** [comment]
After further research I suggest to close it. Looks to much complexity is needed to introduce this functionality.

**Comment by donyunardi** [comment]
Thanks everyone for looking into this.
