### ISSUE TITLE
Multi-line comments and modal dismissing

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.reporter#71]
From https://github.com/insightsengineering/coredev-tasks/issues/244

- [ ] From @npaszty when you click in the add card button could the cursor be active in the comment box?
- [ ] ~The add a card to report modal gets closed when you click elsewhere on the app - I don't think that is the right behaviour~
- [ ] If I do this:
![image](https://user-images.githubusercontent.com/15201933/172338941-6ae23265-e0db-4d5e-81d0-d56e27406f3c.png)

I get this:
![image](https://user-images.githubusercontent.com/15201933/172338994-01e771aa-a09f-43f1-a70a-91b7d9f96591.png)

(Although I'm not sure people would agree, being able to add markdown there would be cool)

**Comment by nikolas-burkoff** [comment]
https://stackoverflow.com/questions/66218241/shiny-set-focus-to-input-in-modaldialog

**Comment by Polkas** [comment]
please think of working at the same time on https://github.com/insightsengineering/teal.reporter/issues/131

**Comment by donyunardi** [comment]
> The add a card to report modal gets closed when you click elsewhere on the app - I don't think that is the right behaviour

This is the code that handles that feature:
https://github.com/insightsengineering/teal.reporter/blob/785e7d19287bf8bc27bc2b9ee2d37ab710402bb1/R/AddCardModule.R#L70

Per conversation with PO, the easyClose feature is preferable so we won't change this behavior.

**Comment by chlebowa** [comment]
This seems to do the trick(s):

```
# 1. initiate dialog with focus
#   add JS code to app ui
#   use .find('#<TEXT_AREA_INPUT_ID>').focus()

# 2. multiline comments:
#   replace characters in text input to 
#   output result as HTML

library(shiny)

ui <- fluidPage(
  # ad 1 #
  tags$header(tags$script(type = "text/javascript",
                          HTML("$('body').on('shown.bs.modal', (x) => 
                               $(x.target).find('#text').focus())"))),
  # end ad 1 #
  actionButton("dialog", "press here"),
  # ad 2 #
  htmlOutput("typedtext"),
  # end ad 2; tbc in server function #
  NULL)

server <- function(input, output, session) {

  observeEvent(input[["dialog"]], {
    showModal(modalDialog(
      textAreaInput("text", "type here"),
      size = "s", footer = NULL, easyClose = TRUE
    ))
  })
  
  typed <- reactive(input[["text"]])
  
  output[["typedtext"]] <- renderText(
    # ad 2 ctd #
    typed() %>% 
      gsub("\n", "<br>", ., fixed = TRUE) %>% 
      gsub(" ", "&nbsp;", ., fixed = TRUE)
    # end ad 2 ctd #
  )
}

shinyApp(ui, server, options = list(launch.browser = TRUE))
```

**Comment by asbates** [comment]
@nikolas-burkoff @gogonzo Since `Renderer$render()` uses `rmarkdown::render()`, markdown is already supported.

```
    card1 <- teal.reporter:::ReportCard$new()
    card1$append_text("Header 2 text", "header2")
    card1$append_text("A paragraph of default text")
    card1$append_plot(
     ggplot2::ggplot(iris, ggplot2::aes(x = Petal.Length)) + ggplot2::geom_histogram()
    )

    card2 <- teal.reporter:::ReportCard$new()
    card2$append_text("Header 2 text", "header2")
    card2$append_text("A paragraph of default text", "header2")
    lyt <- rtables::analyze(rtables::split_rows_by(rtables::basic_table(), "Day"), "Ozone", afun = mean)
    table_res2 <- rtables::build_table(lyt, airquality)
    card2$append_table(table_res2)
    card2$append_table(iris)

    reporter <- teal.reporter:::Reporter$new()
    reporter$append_cards(list(card1, card2))

    yaml_l <- list(
      author = teal.reporter:::yaml_quoted("NEST"),
      title = teal.reporter:::yaml_quoted("Report"),
      date = teal.reporter:::yaml_quoted("07/04/2019"),
      output = list(html_document = list(toc = FALSE))
    )

    yaml_header <- teal.reporter:::md_header(yaml::as.yaml(yaml_l))
    result_path <- teal.reporter:::Renderer$new()$render(reporter$get_blocks(), yaml_header)
```

The result is

![image](https://user-images.githubusercontent.com/36482959/196247187-31489f15-2d33-47b8-88df-445d7a1c6732.png)
