### ISSUE TITLE
Enhance buttons styling

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.reporter#88]
### Feature description

As an example:
Convert this:
![image](https://user-images.githubusercontent.com/12943682/176397211-f482713b-3d16-4a59-945a-7cc5d1894527.png)

Into this:
![image](https://user-images.githubusercontent.com/12943682/176397308-67f01589-8855-4943-8f9a-1c46bb6c41e8.png)

Right now colourful and wide buttons are super eye-catching whereas this is the visualisation that should be the main point of interest. Please make it more "light" so that we would keep the hierarchy right.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Polkas** [comment]
This proposal is better for the users who already know this functionality. We have to be careful here.

**Comment by pawelru** [comment]
> This proposal is better for the users who already know this functionality. We have to be careful here.

Yeah that's the goal. I think it's fair to assume that the teal app users would use it more than ~once~ few times therefore we can be less verbose explaining what a given button is doing. There is some learning and adaptation period required but after this it should be pretty straightforward. I do want to have a constant GUI throughout the lifecycle of that functionality - in particular not long labels for couple of months for adaptation and only then more minimal option.

**Comment by Polkas** [comment]
We have to remember that teal.reporter is design with the attitude of "a regular shiny user first".
I like your comment that as users are learning so the UI could change too.
Then we have to think about supporting two different UIs, the current more verbose and proposed by you.
It could be done very easily with an additional argument to the ui function of the module, like type = "verbose".

**Comment by pawelru** [comment]
> We have to remember that teal.reporter is design with the attitude of "a regular shiny user first".
> 
> I like your comment that as users are learning so the UI could change too.
> 
> Then we have to think about supporting two different UIs, the current more verbose and proposed by you.
> 
> It could be done very easily with an additional argument to the ui function of the module, like type = "verbose".

Oh no! This is exactly something that I would like to avoid! We need to have one version only and the simpler the better.

**Comment by npaszty** [comment]
how about something like this
![image](https://user-images.githubusercontent.com/40777373/177559170-90a2e9ae-378a-4b7a-931a-2a9a4c9b4589.png)

**Comment by Polkas** [comment]
This should be done by proper styling of the class for simpleReporter module.
WHen it is ready the simpleReporter should be applied to all of the repos:

- [ ] teal.modules.general
- [ ] teal.modules.clinical
- [ ] teal.modules.hermes
- [ ] teal.modules.osprey
- [ ] teal.modules.goshawk

we want to update in each module:

SRV:

```
# FROM
      teal.reporter::add_card_button_srv("addReportCard", reporter = reporter, card_fun = card_fun)
      teal.reporter::download_report_button_srv("downloadButton", reporter = reporter)
      teal.reporter::reset_report_button_srv("resetButton", reporter)
# TO
      teal.reporter::simple_reporter_srv("simple_reporter", reporter = reporter, card_fun = card_fun)
```

UI:

```
# FROM
      shiny::tags$div(
        teal.reporter::add_card_button_ui(ns("addReportCard")),
        teal.reporter::download_report_button_ui(ns("downloadButton")),
        teal.reporter::reset_report_button_ui(ns("resetButton"))
      ),
# TO
teal.reporter::simple_reporter_ui("simple_reporter")
```

**Comment by gogonzo** [comment]
1. Change simple_reporter_module with the css rules
2. Replace add_card_button_srv, download_report_button_srv with simple_reporter_module_srv in each tlg-module

**Comment by mhallal1** [comment]
@Polkas updated the css is his PR
@mhallal1 updated all repos to use `simple_reporter`

**Comment by mhallal1** [comment]
@Polkas the second options looks good to me.
