### ISSUE TITLE
Capture renderer error and notify user

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.reporter#89]
### Feature description

Using my local setup I ended up with render to pdf errors:
```
Warning: Error in : LaTeX failed to compile /private/var/folders/m1/hrz0h_ls7gz57rc80tnj41t80000gp/T/RtmpvGtFr3/report_202206291210060291/input_20220629121006031.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See input_20220629121006031.log for more info.
  [No stack trace available]
Warning in system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  error in running command
! sh: pdflatex: command not found
```

As an app user I want to be notified that something is not worked as I might not have access to the console.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Polkas** [comment]
It have to be check as we already adding a try for this process
