### ISSUE TITLE
Editable Card names

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.reporter#94]
When we get the Add Card Modal we should add there a Card Name field additionally to already asked comment.
This Title will be used only for the Preview purposes or should we use it for the Card title (Block) too?
This will help to distinguish many cards from the same module , now they could easily have the same name in the previewer.

**Comment by gogonzo** [comment]
Beware these names should be reproducible from archiver.

**Comment by nikolas-burkoff** [comment]
Also from https://github.com/insightsengineering/teal.modules.hermes/issues/284#issuecomment-1268882154 - could the default name be the name of the label of the module

**Comment by danielinteractive** [comment]
thanks @nikolas-burkoff for linking this here. I think that would be ideal if it can work with the teal reporter framework.

**Comment by Polkas** [comment]
linked to :https://github.com/insightsengineering/teal.reporter/issues/35

**Comment by lcd2yyz** [comment]
Linking to https://github.com/insightsengineering/teal.reporter/issues/150
Make sense to use module label for card name as default, but allowing card name to be editable.

**Comment by mhallal1** [comment]
@lcd2yyz @danielinteractive we decided with @nikolas-burkoff and @Polkas that we will not pass the module label to the reporter cards before teal refactor is accomplished. `label` argument will have to be passed from `tm_g_XXX` to `srv_g_xxx` of all modules using reporter to accomplish this task. 
Therefore, the decision right now is to keep the static assignment of the name to cards and add the option to modify the card name using UI pop up, please refer to the under development PR: https://github.com/insightsengineering/teal.reporter/pull/172
