### ISSUE TITLE
Optional Show R Code in the Report

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.reporter#95]
We should think about global and local switches in the Previewer so sb could decided if want to add the Show R Code into the Card. The SHow R Code could be easily very voluminous so it could be desirable to have such functionality.

**Comment by gogonzo** [comment]
One global witch for all cards.

**Comment by Polkas** [comment]
Please consider a new knitr functionality of ````{comment} chunks for turn off Show R Code

Or with `echo =` TRUE or FALSE (turn off with required functionality) and always eval = FALSE. 
We could paste the code directly to the chunk.

**Comment by nikolas-burkoff** [comment]
Duplicate of #131

**Comment by donyunardi** [comment]
Closing as duplicate.
